# Generated by Django 4.1.2 on 2022-10-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='text',
        ),
    ]
