# Generated by Django 4.1.2 on 2022-10-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0002_rename_caption_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('S', 'Storytime'), ('V', 'Vent'), ('C', 'Confession'), ('I', 'Idea'), ('A', 'Advice'), ('O', 'Opionion'), ('W', 'Create Writing')], default='Storytime', max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_app.post')),
            ],
        ),
    ]
