# Generated by Django 4.1.2 on 2022-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='That time when..', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.CharField(choices=[('S', 'Storytime'), ('V', 'Vent'), ('C', 'Confession'), ('I', 'Idea'), ('A', 'Advice'), ('O', 'Opionion'), ('W', 'Creative Writing')], default='Storytime', max_length=1),
        ),
    ]
