# Generated by Django 4.1.2 on 2022-10-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0005_alter_category_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='the_app.category'),
        ),
    ]
