# Generated by Django 4.1.2 on 2022-10-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0009_alter_category_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.CharField(max_length=50),
        ),
    ]
